---
title: "First_GitHub_Rmarkdown_BIOL4315"
author: "Mike Wu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# How to connect an R project to your GitHub Account

Install packages of "vegan" and "ggplot2" and load them.
```{r loading packages, message=FALSE, warning=FALSE, eval = T, results = 'hide'}
# install packages first
install.packages('vegan',
    repos = c('https://vegandevs.r-universe.dev','https://cloud.r-project.org'))
install.packages("ggplot2", repos = 'https://cloud.r-project.org')

# load packages
library(vegan)
library(ggplot2)

```

Load Dune dateset and log1p transform it
```{r dune}
data(dune)
dune2 <- dune
dune2_log1p <- log1p(dune2)  # log1p transform dune

```

Get the nmds from dune dataset and the points
```{r nmds, message=FALSE, warning=FALSE, results = 'hide'}
dune_nmds <- metaMDS(dune2)
dpoints <- dune_nmds$points

```

Create a scatterplot for dune dataset after NMDS
```{r plotting, message=FALSE, warning=FALSE}
dpoints <- data.frame(dpoints)
scatterplot_dune <- ggplot(data = dpoints, mapping = aes(MDS1, MDS2)) +
  geom_point() +
  ggtitle("Scatterplot of MDS1 vs MDS2 for dune dataset after NMDS") + 
  theme_bw()

scatterplot_dune
ggsave("scatterplot.pdf", plot = scatterplot_dune)
```